### ISSUE TITLE
change update frequency 

### ISSUE THREAD

**Issue by medellin9** [philippnormann/chia-monitor#36] opened 2021-07-25 22:01 UTC
Hi,

how can I reduce the update frequency of chia-monitor to get less CPU usage from the monitor? It's currently using about 4-5% of my CPU, which I would like to reduce.

**Comment by gryan315** [comment] 2021-08-02 13:53
@philippnormann I've noticed the constant scraping by the monitor is using nearly 30W on my system, what would be the easiest way to insert a delay timer for the asyncio on all the collectors?

**Comment by gryan315** [comment] 2021-08-02 21:47
Just thought I'd update you on my fix for this: I changed the `asyncio.sleep()` timer from the default 10 seconds to 120 on both the rpc_collector.py at line 200 and price_collector.py at line 48. This has significantly reduced my CPU usage and I may increase the interval further since most of those stats don't change very often. It still pulls realtime farming info from the ws_collector.py.

**Closed** 2021-08-07 14:19 UTC

**Comment by philippnormann** [comment] 2021-08-07 14:33
Hey @medellin9 and @gryan315, thanks for your input! Efficiency optimizations haven't been focused on yet, but if your claims of 30W are correct, that sounds like we need to be more careful in our resource usage. Although I couldn't reproduce your numbers with my system (with a Ryzen 5 3400G, `powertop` reports an estimated power usage for the chia-monitor of 150mW-200mW), I pushed an update that allows all update frequencies to be customized using the `config.json`. With the new default of 10 seconds for the notification refresh interval, the estimated power usage dropped to roughly 5mW in my setup. Hope this helps ✌🏽
