### ISSUE TITLE
sth went wrong 

### ISSUE THREAD

**Issue by Waldkotz** [philippnormann/chia-monitor#3] opened 2021-06-18 11:33 UTC
Hi,

first of all. Thanks for your great work.
Today after updating i cant get it to run. 

Even tried complete reinstall.

error:

```x@y:~/chia-monitor$ pipenv run python -m monitor
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chia/chia-monitor/monitor/__main__.py", line 85, in <module>
    lost_plots_alert_threshold = config["notifications"]["lost_plots_alert_threshold"]
KeyError: 'lost_plots_alert_threshold'
```

any suggestions?

**Comment by philippnormann** [comment] 2021-06-18 14:04
Hey @Waldkotz, glad you like it and thanks for reporting this issue! :)

This somewhat cryptic error message means your `config.json` is out of date and is missing the `lost_plots_alert_threshold` parameter under `notifications`. Please compare your local `config.json` with the provided example `config-example.json` and make sure all the fields are matching.

But I agree that we should get better error messages for this type of error and maybe also add some explanation on this update process to the `README.md`.

**Comment by Waldkotz** [comment] 2021-06-18 14:28
Thanks the line 
`"lost_plots_alert_threshold": 1,`
was missing.

now its working a litte more. still getting no output.
tried to reinstall.
after runnning ` pipenv run python -m monitor` there is no output `strg+c` results to `bye` and the error massages.

```
x@y:~$ cd chia-monitor/
x@y:~/chia-monitor$ pipenv install
Installing dependencies from Pipfile.lock (70a85a)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 53/53 — 00:00:12
To activate this project's virtualenv, run the following:
 $ pipenv shell
x@y:~/chia-monitor$ pipenv run alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 0d96de75543b, Create inital event model
INFO  [alembic.runtime.migration] Running upgrade 0d96de75543b -> d5e37981194d, Add total_plots column to farming events table
INFO  [alembic.runtime.migration] Running upgrade d5e37981194d -> 9c7abcc3ed80, Add host column to harvester_events table
INFO  [alembic.runtime.migration] Running upgrade 9c7abcc3ed80 -> 5ae65fde6009, Add harvester_count column to connection_events table
x@y:~/chia-monitor$ screen -S chia-mon
x@y:~/chia-monitor$ pipenv run python -m monitor
^C
2021-06-18T16:23:44.266 INFO   👋 Bye!
2021-06-18T16:23:44.330 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa089234d90>
2021-06-18T16:23:44.330 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa089234310>
2021-06-18T16:23:44.330 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa089234b80>
2021-06-18T16:23:44.330 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa0891c7670>
2021-06-18T16:23:44.330 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa0891c70a0>
x@y:~/chia-monitor$
```

**Comment by Waldkotz** [comment] 2021-06-18 14:32
BTW 
```
x@y:~/chia-monitor$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
x@y:~/chia-monitor$ uname -r
5.11.0-18-generic
x@y:~/chia-monitor$
```

**Comment by philippnormann** [comment] 2021-06-18 17:10
Very weird 🤔 I suspect the program might hang during the creation of the API collectors.
To further debug the root cause of this issue, I added some logging before each collector is created.
Could you please update to the latest version and try again? 
You can also join our Discord support channel, where we can try to debug it together 🙂

**Comment by Waldkotz** [comment] 2021-06-18 19:16
Did the update. 
Now it works. 
Thanks. 
Can you tell me the server?

**Comment by philippnormann** [comment] 2021-06-18 19:55
Awesome, I'll close this issue then 👍🏽 
You can join the server by clicking this [link](https://discord.gg/K5KyD9mXDh).

**Closed by philippnormann** 2021-06-18 19:55 UTC
