### ISSUE TITLE
[BUG] RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by brianjojoray** [philippnormann/chia-monitor#30] opened 2021-07-20 14:51 UTC
I am running perfect with this code for amost 20 hours.
But then there is an error and the monitor stop.

Operating System: Windows 10

Here is the log
```
2021-07-20T17:18:40.174 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001E9EE70D670>
transport: <_ProactorSocketTransport fd=2804 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001E9EA4B80D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by philippnormann** [comment] 2021-07-21 23:29
Hey @brianjojoray, thanks for reporting this issue! I suspect that the error log you posted is just the last exception and not the root cause of the crash. Are you sure that the stack trace you posted is complete? To know what caused this crash, we need the first (uppermost) exception from the stack trace.

**Comment by brianjojoray** [comment] 2021-07-22 13:56
'''
2021-07-22T09:10:13.210 INFO   🔏 Signage Point Index: 53
2021-07-22T09:10:13.210 INFO   🎰 Challenge Hash: 0x4e4cb30884112b39fd253fb065f2a68ec4b50aa2103547c5a14b55c5c162657d
2021-07-22T09:10:13.210 INFO   ⌛ Signage Point: 0xf6931346b3a174e34b80131d2f4cedc9b199c4a891943709e61e570bbc782d22
Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Python\Python39\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Python\Python39\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Python\Python39\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Python\Python39\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.IntegrityError: UNIQUE constraint failed: signage_point_events.ts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "J:\code\chia-monitor\monitor\__main__.py", line 136, in <module>
    asyncio.run(aggregator(exporter, notifier))
  File "C:\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "J:\code\chia-monitor\monitor\__main__.py", line 77, in aggregator
    await persist_event(event)
  File "J:\code\chia-monitor\monitor\__main__.py", line 39, in persist_event
    await db_session.commit()
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 333, in commit
    return await greenlet_spawn(self.sync_session.commit)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 129, in greenlet_spawn
    result = context.switch(value)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3298, in flush
    self._flush(objects)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 3398, in _flush
    flush_context.execute()
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\orm\persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Python\Python39\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Python\Python39\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Python\Python39\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Python\Python39\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Python\Python39\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: signage_point_events.ts
[SQL: INSERT INTO signage_point_events (ts, challenge_hash, signage_point, signage_point_index) VALUES (?, ?, ?, ?)]
[parameters: ('2021-07-22 09:10:13.194766', '0x4e4cb30884112b39fd253fb065f2a68ec4b50aa2103547c5a14b55c5c162657d', '0xf6931346b3a174e34b80131d2f4cedc9b199c4a891943709e61e570bbc782d22', 53)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2021-07-22T09:10:13.725 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018DEFB0E880>
2021-07-22T09:10:13.725 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018DEFB03B20>
2021-07-22T09:10:13.725 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018DEFAFDF10>
2021-07-22T09:10:13.725 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018DEFB0E100>
2021-07-22T09:10:13.725 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018DEFB0E5E0>
2021-07-22T09:10:13.725 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DEFB03550>
transport: <_ProactorSocketTransport fd=1192 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function ClientResponse.__del__ at 0x0000018DEEB2FF70>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 803, in __del__
  File "C:\Python\Python39\lib\site-packages\aiohttp\connector.py", line 170, in release
  File "C:\Python\Python39\lib\site-packages\aiohttp\connector.py", line 650, in _release
  File "C:\Python\Python39\lib\site-packages\aiohttp\client_proto.py", line 63, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-22T09:10:13.757 ERROR  Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000018DF0BD7D60>, 282064.734)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000018DEFB03AF0>
2021-07-22T09:10:13.757 ERROR  Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000018DEFB1EB20>, 282060.421), (<aiohttp.client_proto.ResponseHandler object at 0x0000018DF0B587C0>, 282060.437)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000018DEFAFDF40>
2021-07-22T09:10:13.757 ERROR  Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000018DEFB705E0>, 282060.937)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000018DEFB0E550>
2021-07-22T09:10:13.757 ERROR  Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000018DF0DEDBE0>, 282060.453), (<aiohttp.client_proto.ResponseHandler object at 0x0000018DEFB70AC0>, 282060.453), (<aiohttp.client_proto.ResponseHandler object at 0x0000018DF0B747C0>, 282060.453)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000018DEFB0E040>
2021-07-22T09:10:13.757 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DF19B0880>
transport: <_ProactorSocketTransport fd=2292 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000018DECA590D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-22T09:10:13.757 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DEFB0E340>
transport: <_ProactorSocketTransport fd=1264 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000018DECA590D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-22T09:10:13.772 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DEFB0E520>
transport: <_ProactorSocketTransport fd=1096 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000018DECA590D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-22T09:10:13.772 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DEFB0EB20>
transport: <_ProactorSocketTransport fd=1116 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000018DECA590D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-22T09:10:13.772 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DF0CEF5B0>
transport: <_ProactorSocketTransport fd=1876 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000018DECA590D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-22T09:10:13.772 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DF0C95C40>
transport: <_ProactorSocketTransport fd=2828 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000018DECA590D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-22T09:10:13.772 ERROR  Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000018DF15A5820>
transport: <_ProactorSocketTransport fd=1352 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000018DECA590D0>
Traceback (most recent call last):
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
PS J:\code\chia-monitor>
'''

**Comment by brianjojoray** [comment] 2021-07-22 13:57
All the log above.Please help

**Comment by philippnormann** [comment] 2021-07-22 14:35
Alright! The first error in your stack trace is `sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: signage_point_events.ts
[SQL: INSERT INTO signage_point_events (ts, challenge_hash, signage_point, signage_point_index) VALUES (?, ?, ?, ?)]` which is a duplicate of https://github.com/philippnormann/chia-monitor/issues/29 and should be fixed since https://github.com/philippnormann/chia-monitor/commit/0b92e155a96d0ffcb3a1646d9f1ebb8b22c2ae43. So please update to the latest version and tell me in https://github.com/philippnormann/chia-monitor/issues/29 if this resolves the issue for you.

**Closed by philippnormann** 2021-07-22 14:35 UTC

**Comment by brianjojoray** [comment] 2021-07-28 18:08
Thanks.
It's already fixed by update to the lastest version.
